version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception_network
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    restart: always
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception_network

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/mariadb
      o: bind
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind

networks:
  inception_network:
    name: inception_network
    driver: bridge