version: "3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: my-mariadb
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    # volumes:
    #   - database:/var/lib/mysql

# volumes:
#   database:
#     name: database
#     driver: local
#     driver_opts:
#       type: none
#       device: ${HOME}/data/mariadb
#       o: bind